services:
  kafka:
    image: confluentinc/cp-kafka:7.5.1
    hostname: kafka
    ports:
      - '9092:9092'
    environment:
      - CLUSTER_ID=YzM3NTBhZWQyZTZjNDhmMT
      - KAFKA_NODE_ID=1
      - KAFKA_LISTENERS=INTER://kafka:29092,CTRL://kafka:29093,PUBLIC://0.0.0.0:9092
      - KAFKA_ADVERTISED_LISTENERS=INTER://kafka:29092,PUBLIC://localhost:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CTRL:PLAINTEXT,INTER:PLAINTEXT,PUBLIC:PLAINTEXT
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka:29093
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTER
      - KAFKA_CONTROLLER_LISTENER_NAMES=CTRL
